#!/bin/sh

ENABLED=yes
PROCS=v2ray
ARGS=""
PREARGS=""
DESC=$PROCS
PATH=/opt/etc/v2ray/:/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
